name: Lint, Build and Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ› Setup Node
        if: github.event.action != 'closed'
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: 'yarn'

      - name: âš™ï¸ Install
        if: github.event.action != 'closed'
        run: yarn

      - name: ğŸ¨ Lint JS
        if: github.event.action != 'closed'
        run: yarn lint

      - name: ğŸ¨Test
        if: github.event.action != 'closed'
        run: |
          yarn playwright install
          yarn test

      - name: ğŸ›  Build (@/pr-preview/pr-${{ github.event.number }})
        if: github.event.action != 'closed'
        run: STORYBOOK_BASE_URL=/pr-preview/pr-${{ github.event.number }} yarn build-storybook

      - name: ğŸš¢ Deploy preview
        uses: rossjrw/pr-preview-action@v1.2
        with:
          source-dir: ./storybook-static/
