name: Build and deploy to GH Pages

on:
  push:
    branches: [main]

concurrency: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ› Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: âš™ï¸ Install Yarn
        run: npm install -g yarn

      - name: ğŸ› Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'yarn'

      - name: âš™ï¸ Install
        run: yarn

      - name: ğŸ¨ Lint JS
        run: yarn lint

      - name: ğŸ¨Test
        run: |
          yarn playwright install --with-deps
          yarn test

      - name: ğŸ›  Build (@/lukso-components)
        run: STORYBOOK_BASE_URL=/lukso-components yarn build-storybook

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: storybook-static # The folder the action should deploy.
          clean-exclude: pr-preview/

      - name: Publish NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
